# Generated by Django 5.1.1 on 2024-10-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='loc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
